##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dripcult/app.dripculture.com.au/newUi/
    - /bin/cp -R partner $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R icons $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp coupon_gen.html $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp login.php $DEPLOYPATH
